/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./mocks";
export type { mocks };
import type * as usdtSol from "./usdt.sol";
export type { usdtSol };
import type * as vnstProxySol from "./vnst.proxy.sol";
export type { vnstProxySol };
import type * as vnstUpgradeSol from "./vnst.upgrade.sol";
export type { vnstUpgradeSol };
